---
swagger: "2.0"
info:
  description: |-
    API criada para o desafio da empresa PontoTel.
     O desafio consistia em consumir de forma assíncrona a API da Alpha Vantage para informar dados do Ibovespa e cotações das 10 maiores empresas brasileiras.
  version: 1.0.0
  title: Desafio PontoTel
  contact:
    name: Tiago Siqueira Dionizio
    email: tiagosdionizio@gmail.com
host: virtserver.swaggerhub.com
basePath: /TiagoSD22/Alpha-Vantage-API/1.0.0
tags:
- name: Ibovespa atual
  description: Obtém o índice bovespa atual
- name: Top empresas
  description: Obtém a lista das 10 maiores empresas brasiliras
- name: Cotação empresarial
  description: Informações de cotações de uma empresa
schemes:
- https
paths:
  /bvsp-intraday/{timeInterval}:
    get:
      tags:
      - Ibovespa atual
      description: |
        Faz uma chamada para a api do Alpha Vantage para obter o valor atual do índice Bovespa e informações como seus valores de alta, baixa e abertura desde o começo do dia até o atual  momento. O intervalo de tempo para coleta dos dados é passado como parâmetro na requisição.
      produces:
      - application/json
      parameters:
      - name: timeInterval
        in: path
        description: intervalo de tempo entre os dados coletados pela api do Alpha Vantage
        required: true
        type: integer
        format: int32
        enum:
        - 1
        - 5
        - 15
        - 30
        - 60
      responses:
        200:
          description: |
            lista de pontos de cotações do Ibovespa no dia
          schema:
            type: array
            items:
              $ref: '#/definitions/StockQuoteData'
        400:
          description: |
            muitas requisições feitas por minuto (máximo de 5/min para a api do Alpha Vantage)
        406:
          description: intervalo de tempo inválido
  /get-top-10:
    get:
      tags:
      - Top empresas
      description: |
        Consulta no banco de dados do servidor as 10 maiores empresas brasileiras cadastradas com base no seu rank.
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: lista das empresas
          schema:
            type: array
            items:
              $ref: '#/definitions/Company'
        500:
          description: falha ao se comunicar com o banco de dados.
  /get-company-stock/{companySymbol}:
    get:
      tags:
      - Cotação empresarial
      summary: obtém cotação da empresa
      description: |
        Consulta, utilizando a api do Alpha Vantage, a cotação de uma empresa especificada pelo seu código
      produces:
      - application/json
      parameters:
      - name: companySymbol
        in: path
        description: símbolo da empresa a qual se deseja buscar a atual cotação
        required: true
        type: string
        enum:
        - OIBR-C
        - BRKM5.SAO
        - ITSA4.SAO
        - JBSS3.SAO
        - ELET6.SAO
        - BBAS3.SAO
        - VALE3.SAO
        - BBDC4.SAO
        - ITUB4.SAO
        - PETR4.SAO
      responses:
        200:
          description: cotação atual da empresa buscada
          schema:
            $ref: '#/definitions/CompanyStock'
        400:
          description: |
            muitas requisições feitas por minuto (máximo de 5/min para a api do Alpha Vantage)
        406:
          description: símbolo de empresa inválido
  /update-company-stock:
    put:
      tags:
      - Cotação empresarial
      summary: atualiza cotação de uma empresa em banco
      description: |
        Atualiza os dados da cotação de uma empresa salva em banco de acordo com o símbolo da empresa a qual a cotação recebida específica.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: companyStock
        description: Cotação a ser salva em banco
        required: false
        schema:
          $ref: '#/definitions/CompanyStock'
      responses:
        200:
          description: dados persistidos em banco com sucesso
        400:
          description: erro ao persistir dados em banco
        405:
          description: método não permitido
definitions:
  StockQuoteData:
    type: object
    properties:
      open:
        type: number
      high:
        type: number
      low:
        type: number
      close:
        type: number
      volume:
        type: number
      timeStamp:
        type: string
        format: date-time
  CompanyStock:
    type: object
    properties:
      lastUpdate:
        type: string
        format: date-time
      price:
        type: number
      volume:
        type: number
      change:
        type: number
      changePercent:
        type: number
      companySymbol:
        type: string
  Company:
    type: object
    properties:
      name:
        type: string
      symbol:
        type: string
      region:
        type: string
      rank:
        type: number
      sector:
        type: string
      stock:
        $ref: '#/definitions/CompanyStock'
